BOOTMAGIC_ENABLE = no
MOUSE_KEY = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
BACKLIGHT_ENABLE = no
MIDI_ENABLE = no
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
FAUXCLICKY_ENABLE = yes
VARIABLE_TRACE = no
API_SYSEX_ENABLE  = no
KEYLOCK_ENABLE = no

TAP_DANCE_ENABLE = yes


